#!/bin/bash
echo "installing..."
chmod +x kvartfetch config
if [[ "$1" == "-t" ]]
        then
        echo "termux installation"
        cp kvartfetch $HOME/../usr/bin
        mkdir -p $HOME/../usr/share/doc/kvartfetch
        cp config $HOME/../usr/share/doc/kvartfetch
else
        cp kvarfetch /bin/kvarfetch
        mkdir -p /usr/share/doc/kvartfetch
        cp config /usr/share/doc/kvartfetch
fi
echo "all done! Copy config file to $HOME/.config/kvartfetch/config !"
echo "you can find default config in /usr/share/doc/kvartfetch"
echo "($HOME/../usr/share/doc/kvartfetch in termux)
exit 0
