#!/bin/bash
set -a
source $HOME/.config/kvarfetch/config


echo -e "\033[35mKVARTIRA FETCH\033[0m"
echo -e "-----------------------"
echo -e "\033[31mАдрес: $ADDRES"
echo -e "\033[36mЦена: $PRICE\033[0m"
echo -e "\033[34mКомнат: $ROOMS\033[0m"
echo -e "-----------------------"
echo -e "\033[36mТип недвижимости: \033[32m$TYPE"
echo -e "\033[36mПлощадь кухни: \033[32m$KITCHEN"
echo -e "\033[36mЭтаж: \033[32m$FLOOR"
echo -e "\033[36mЭтажность дома: \033[32m$FLOORS"
echo -e "\033[36mОбщая площадь: \033[32m$ALLSPACE"
echo -e "\033[36mЖилая площадь: \033[32m$LIVINGSPACE"
