#!/bin/busybox ash
set -a
if [ -e /usr/share/doc/kvartfetch/config ]; then
        if [ -e $HOME/.config/kvartfetch/config ]; then
                source $HOME/.config/kvartfetch/config
        else
                source /usr/share/doc/kvartfetch/config
        fi
else
        if [ -e $HOME/../usr/share/doc/kvartfetch ]; then
                source $HOME/../usr/share/doc/kvartfetch
        else
                echo "Cannot find config! Exit..."
                exit 1
        fi
fi


#colors
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${blue}"         # labels
ic="${reset}"                       # info
c0="${reset}${blue}"                # first color
na="${reset}${magenta}"		    # name	
ad="${reset}${red}"		    # addres
ro="${reset}${cyan}"		    # rooms
et="${reset}${green}"
## OUTPUT

cat <<EOF

${c0} _____    ${na}KVARTIRA FETCH${reset}
${c0}|o o o|   -------------------------
${c0}|o o o|   ${ad}Адрес:     ${ADDRES}${reset}
${c0}|o o o|   ${lc}Цена:      ${PRICE}${reset}
${c0}|o o o|   ${ro}Комнат:    ${ROOMS}${reset}
${c0}|o o o|   -------------------------
${c0}|o o o|   ${lc}Этаж:      ${et}${FLOOR}${reset}
${c0}|o o o|   ${lc}Тип:       ${et}${TYPE}${reset}
${c0}|_[]__|   ${lc}Площадь:   ${et}${ALLSPACE}${reset}
EOF
